### ISSUE TITLE
Meta Changes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#2070]
Stats for the past 30 days:

![image](https://user-images.githubusercontent.com/63279022/168539757-ba89f10a-4758-491e-b892-0989a242bc5d.png)

Based on this I'd like to:

- [ ] Nerf Summon Power's effect in duels (that's where it seems to be too strong).
- [ ] Remove the spell lifesteal from Starforce and make Luminance not affected by spell amp (so tanks won't need/want to buy Starforce, therefore reducing Starforce's pickrate). 
- [ ] Buff Luminance's Blaze damage to compensate for the loss of spell amped damage.
- [ ] Make Starforce build from something like Ethereal blade instead to compensate for it's loss of spell lifesteal.
- [ ] Rework Devastator to have something more useful for pvp than armor reduction. The main weakness of melee right clickers is getting kited, so a magic immunity piercing slow or bash on attack makes the most sense to me.

**Comment by jakmarles** [comment]
Remove the spell lifesteal from Starforce and make Luminance not affected by spell amp (so tanks won't need/want to buy Starforce, therefore reducing Starforce's pickrate). - without a source of lifesteal tanks will be useless. tanks cant rly use satanic efficently or regen from spells

**Comment by PonyashaWright** [comment]
1) Nerf Summon Power's effect in duels (that's where it seems to be too strong).

Not every summoner skill is good for duels tho (some of the summons are killed really easily and do don't that much). I'd like for this to have effect only on some summon skills, which are strong for duels instead.

2) Remove the spell lifesteal from Starforce and make Luminance not affected by spell amp (so tanks won't need/want to buy Starforce, therefore reducing Starforce's pickrate).
3) Buff Luminance's Blaze damage to compensate for the loss of spell amped damage.
4) Make Starforce build from something like Ethereal blade instead to compensate for it's loss of spell lifesteal.

I like these ideas, but I feel like some magical tanks builds would still want to buy ethereal for spell lifesteal amplification and it's active, but yeah, it would reduce it's pickrate, which is good.

5) Rework Devastator to have something more useful for pvp than armor reduction. The main weakness of melee right clickers is getting kited, so a magic immunity piercing slow or bash on attack makes the most sense to me.

I disagree. Both Devastator and Boomstick should be viable only for creeps, at least that's how I see it, since nobody actually competent in duels uses Boomstick if they something to replace it with. Surviving with range hero is easier itself, since you can just kite most creeps easily, and I feel like Devastator's bad stats in comparison with Boomstick isn't related to duel kiting, since there are already plenty of duel items to prevent that.

If you want to treat melee carries, I'd suggest adding new item instead (something like upgraded diffusal blade with abyssal, If the stats are going to be buffed upon fusion, make ranged heroes have the standard DB's manaburn instead of buffed). Optionally, as for active effect, you can make it dispel the target once, like the old DB did.

**Comment by Draze22** [comment]
> Remove the spell lifesteal from Starforce and make Luminance not affected by spell amp (so tanks won't need/want to buy Starforce, therefore reducing Starforce's pickrate). - without a source of lifesteal tanks will be useless. tanks cant rly use satanic efficently or regen from spells

They could still buy Bloodstone or Eternal Shroud if they want Spell Lifesteal.

**Comment by Draze22** [comment]
> Not every summoner skill is good for duels tho (some of the summons are killed really easily and do don't that much). I'd like for this to have effect only on some summon skills, which are strong for duels instead.

Clearly based on the stats Summons are too strong since they're played almost as much as Casters and Right Clickers despite making up such a small amount of the ability pool, **and** they have the highest winrate. 

The way I'm balancing summons is by making the bad ones better (by increasing how much they get buffed by Summon Power), but not better than Summons that are less affected by Summon Power. Basically reducing the gap in power between the different Summons while also keeping the order of which Summons are best. I'm pretty happy with this atm since all Summons are top 50% abilities and best Summons (Spirit Bear and MSW) are roughly top 10 abilities.

That's why I want to nerf all Summons, rather than just the best ones and as I mentioned Summons seem strongest in duels so nerfing their power there makes the most sense.

> I disagree. Both Devastator and Boomstick should be viable only for creeps, at least that's how I see it, since nobody actually competent in duels uses Boomstick if they something to replace it with. Surviving with range hero is easier itself, since you can just kite most creeps easily, and I feel like Devastator's bad stats in comparison with Boomstick isn't related to duel kiting, since there are already plenty of duel items to prevent that.
> 
> If you want to treat melee carries, I'd suggest adding new item instead (something like upgraded diffusal blade with abyssal, If the stats are going to be buffed upon fusion, make ranged heroes have the standard DB's manaburn instead of buffed). Optionally, as for active effect, you can make it dispel the target once, like the old DB did.

Boomstick can be useful in duels because of its extra attack range and since Crown, Luminance and Starforce are all good in duels. It makes more sense to me if we make both Boomstick and Devastator strong items for duels, that way all 5 core build items (6 if you include Torture Pipe) are good in both creep rounds and duels.

**Comment by Draze22** [comment]
@jakmarles @PonyashaWright @AustraliaIsMyCity anything more to add?

**Comment by jakmarles** [comment]
Maybe a nerf of pipe damage amplification in duels on pure dmg type spells? Or make those epells not affect magic immune enemies
